### ISSUE TITLE
Github Pages to show off our presentations?

### ISSUE THREAD

**Issue by wesruv** [backdrop-ops/slides#2]
I just made a gh-pages branch so we have this now:
http://backdrop-ops.github.io/slides/#/

Was thinking when/if we get more presentations in here the index can link to the different presentations.

@jenlampton 
What do you think of getting rid of the master branch and just rocking the `gh-pages` branch?

**Comment by jenlampton** [comment]
I think that sounds like a good plan :)

**Comment by wesruv** [comment]
@jenlampton I don't have the perms to change the default branch, and it looks like I can't delete the master branch because it's the default branch.

**Comment by quicksketch** [comment]
I switched the default branch to gh-pages, master seemed to disappear immediately. Odd, but it seems to be gone now. :)
